### ISSUE TITLE
[BUG] Weird message when building the app ( investigate )

### ISSUE THREAD

**Issue by pblvrt** [streamethorg/streameth-platform#659]
**Describe the bug**
When building the app, I see this error message

`n [Error]: Dynamic server usage: no-store fetch https://api.streameth.org/organizations/protolayers /protolayers
    at /Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:8558
    at /Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:15891
    at a.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:8884)
    at c.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:3084)
    at c.startActiveSpan (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:18139)
    at a.startActiveSpan (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:18673)
    at /Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:15424
    at a.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:8884)
    at c.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:3084)
    at b.trace (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:15378) {
  description: 'no-store fetch https://api.streameth.org/organizations/protolayers /protolayers',
  digest: 'DYNAMIC_SERVER_USAGE'
}
n [Error]: Dynamic server usage: no-store fetch https://api.streameth.org/organizations/party_action_people /party_action_people
    at /Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:8558
    at /Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:15891
    at a.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:8884)
    at c.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:3084)
    at c.startActiveSpan (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:18139)
    at a.startActiveSpan (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:18673)
    at /Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:15424
    at a.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:8884)
    at c.with (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:1:3084)
    at b.trace (/Users/pablovoorvaart/Code/streameth-platform/packages/app/.next/server/chunks/4522.js:2:15378) {
  description: 'no-store fetch https://api.streameth.org/organizations/party_action_people /party_action_people',
  digest: 'DYNAMIC_SERVER_USAGE'
}`

**To Reproduce**
1. Build the app on local

**Expected behavior**
Organization pages should be statically generated, this is saying that is dynamically generated I think

**Comment by greatsamist** [comment]
Issue resolved. There was a generateStaticParams function causing issues due to its asynchronous behavior and unnecessary code execution on the organization page.
```
export async function generateStaticParams() {
  const organizations = await fetchOrganizations();
  const paths = organizations.map((organization) => ({
    organization: organization.slug,
  }));
  return paths;
}
```

### Fix
Remove unused code
see in https://github.com/streamethorg/streameth-platform/commit/a74313948aa7ebd49378af0523d49f98503e57c3
